# Generated by Django 2.2.7 on 2022-11-26 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institutes',
            fields=[
                ('number_Institute', models.TextField(verbose_name='институт')),
                ('group', models.TextField(verbose_name='номер')),
                ('id_group', models.TextField(primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_week', models.TextField(verbose_name='день')),
                ('day_week', models.TextField(verbose_name='день неделе')),
                ('lesson_score', models.TextField(verbose_name='пара')),
                ('time', models.TextField(verbose_name='время')),
                ('cabinet', models.TextField(verbose_name='кабинет')),
                ('object', models.TextField(verbose_name='предмет')),
                ('teacher', models.TextField(verbose_name='преподаватель')),
                ('idd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser.Institutes')),
            ],
            options={
                'verbose_name': 'расписание',
                'verbose_name_plural': 'расписание',
            },
        ),
    ]
