# Generated by Django 2.2.7 on 2022-11-26 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='idd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='parser.Institutes'),
        ),
    ]
